---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
   namespace: fabric
   name: cli
   labels:
     app: cli
spec:
  replicas: 1
  selector:
    matchLabels:
        app: cli
  template:
    metadata:
      labels:
       app: cli
    spec:
      containers:
        - name: cli
          image: hyperledger/fabric-tools:1.4.2
          imagePullPolicy: Never
          env:
          - name: CORE_VM_ENDPOINT
            value: "unix:///host/var/run/docker.sock"
          - name: GOPATH
            value: "/opt/gopath"
          - name: FABRIC_LOGGING_SPEC
            value: "INFO"
          - name: CORE_PEER_TLS_ENABLED
            value: "true"
          - name: CORE_PEER_PROFILE_ENABLED
            value: "true"
          - name: CORE_PEER_TLS_CERT_FILE
            value: "/etc/hyperledger/crypto-config/peerOrganizations/org1.example.com/peers/peer0org1/tls/server.crt"
          - name: CORE_PEER_TLS_KEY_FILE
            value: "/etc/hyperledger/crypto-config/peerOrganizations/org1.example.com/peers/peer0org1/tls/server.key"
          - name: CORE_PEER_TLS_ROOTCERT_FILE
            value: "/etc/hyperledger/crypto-config/peerOrganizations/org1.example.com/peers/peer0org1/tls/ca.crt"
          - name: CORE_PEER_TLS_CLIENTAUTHREQUIRED
            value: "false"
          - name: CORE_PEER_TLS_CLIENTCERT_FILE  
            value: "/etc/hyperledger/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/tls/client.crt"  
          - name: CORE_PEER_TLS_CLIENTKEY_FILE 
            value: "/etc/hyperledger/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/tls/client.key"  
          - name: CORE_PEER_ID
            value: "cli"
          - name: CORE_PEER_ADDRESS
            value: "peer0org1:30011"
          - name: CORE_PEER_LOCALMSPID
            value: "Org1MSP"
          - name: CORE_PEER_MSPCONFIGPATH
            value: "/etc/hyperledger/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp"
          workingDir: /etc/hyperledger
          command: ["/bin/bash", "-c", "--"]
          args: ["while true; do sleep 30; done;"]
          volumeMounts:
           - mountPath: /host/var/run
             name: run
           - mountPath: /etc/hyperledger/channel-artifacts
             name: certificate
             subPath: channel-artifacts
           - mountPath: /etc/hyperledger/crypto-config
             name: certificate
             subPath: crypto-config
      volumes:
        - name: certificate
          persistentVolumeClaim:
              claimName: fabric-pv
        - name: run
          hostPath:
            path: /var/run

