---
apiVersion: v1
kind: Service
metadata:
   namespace: fabric
   name: peer0org1
   labels:
     peer-id: peer0.org1.example.com
spec:
 selector:
   peer-id: peer0.org1.example.com
 type: NodePort
 ports:
   - name: endpoint
     protocol: TCP
     port: 30011
     targetPort: 30011
     nodePort: 30011
   - name: event
     protocol: TCP
     port: 30012
     targetPort: 30012
     nodePort: 30012  

---
apiVersion: v1
kind: Service
metadata:
   namespace: fabric
   name: peer0org2
   labels:
     peer-id: peer0.org2.example.com
spec:
 selector:
   peer-id: peer0.org2.example.com
 type: NodePort
 ports:
   - name: endpoint
     protocol: TCP
     port: 30021
     targetPort: 30021
     nodePort: 30021
   - name: event
     protocol: TCP
     port: 30022
     targetPort: 30022
     nodePort: 30022
