---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fabric-pv
  labels:
    app: fabric-pv
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /home/www/go/src/github.com/hyperledger/fabric-samples/first-network
    server: 192.168.126.131

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 namespace: fabric
 name: fabric-pv
spec:
 accessModes:
   - ReadWriteMany
 resources:
   requests:
     storage: 10Mi
 selector:
   matchLabels:
     app: fabric-pv

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fabric-pvdata
  labels:
    app: fabric-pvdata
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /home/www/go/src/github.com/hyperledger/fabric-samples/first-network/fabric-data
    server: 192.168.126.131

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 namespace: fabric
 name: fabric-pvdata
spec:
 accessModes:
   - ReadWriteMany
 resources:
   requests:
     storage: 10Gi
 selector:
   matchLabels:
     app: fabric-pvdata

